name: “Bug Report”
description: “Use this template to report a bug in the application.”
title: “[Bug]: ”
labels: [ “bug”, “needs-triage” ]
assignees: []
type: bug

body:
  - type: markdown
    attributes:
      value: |
        **Description**
        A clear and concise description of the problem.

  - type: input
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide the steps to reproduce the issue.
      placeholder: |
        1. …
        2. …
    validations:
      required: true

  - type: input
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The feature should …

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual Behavior
      description: What happened instead of the expected behavior?
      placeholder: The application shows …

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, version, browser (if relevant), database version, etc.
      placeholder: e.g. Ubuntu 22.04, MySQL 8.0, Chrome 116

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Add any further context about the issue here (logs, screenshots, links).
      placeholder: Attach logs or screenshots if available.

  - type: checkboxes
    id: accept_terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue you agree to abide by the project’s Code of Conduct.
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
